apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels: #this are replica set labels
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: nginx
      environment: dev
  template:
    metadata:
      labels: #this are pod labels 
        tier: frontend
        app: nginx
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx
