apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:  #these are deployment labels
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels: #this are pod labels
        app: nginx
        project: roboshop
        component: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
