apiVersion: v2
kind: pod
metadata: 
  name: simple-pod
  namespace: roboshop #here if we wont give any praticular name space it will attach to default namespace
spec: 
  containers: 
  - name: nginx-simple
    image: nginx:1.14.2
    ports: 
    - containerPort: 80

