apiVersion: v1
kind: pod
metadata: 
  name: annotations
  annotations: 
    com.project.author: production
    com.project.name: roboshop
spec: 
  containers: 
  - name: nginx-labels
    image: nginx
    ports: 
    - containerPort: 80

