apiVersion: v1
kind: Pod
metadata: 
  name: resources
spec: 
  containers: 
  - name: nginx
    image: nginx
    imagePullPolicy: Always   #if we mention always here it will get pull images always from docker so, mention always
    resources: 
      requests: 
        cpu: "100m"
        memory: "128Mi"
      limits: 
        cpu: "200m"
        memory: "256Mi"


